### PR TITLE
fix: set relic owner correctly on creation

### LINKED ISSUE #184: [Bug] Manually assigning a relic during relic creation doesn't correctly set the owner
Repro steps:

* Add/import some characters
* Manually "Add new relic" and select an owner for the relic on the modal
* Relic gets created showing the owner avatar, but on the Characters tab it doesn't update their build

Desired behavior: Build updates with the newly created relic & unequips the old relic

### PR DESCRIPTION
**Pull request by Kenste**
# Pull Request

## Description

* Fixed assigning the owner of relic during creation, when relic is originally stored

However, I feel that this fix is rather suboptimal, no?
Would it not make more sense to move this kind of consistency work into `DB` itself?
On the other hand, refactoring `DB` (and also moving it to TS, see #44) seems like a lot of work for a (currently) small gain(?).
Although this is my naive view on these things ^^

Edit:

I have found two more issues (both being fixed):
#### 1. Changing the part of an equipped relic does not correctly assign the relic.
Reproduce:
- Add/import a character
- Add a relic to the character
- Go to the `Characters` screen (to visually see the issue)
- Edit the relic to be of a different part
- The relic should still be visually on the original part, but the score is shown on the new part (see first screenshot)

#### 2. Adding and assigning a relic does not correctly reassign an already equipped relic
Reproduce:
- Add/import a character
- Add a relic to the character
- Add another relic to the same character with the same part
- Relics page should show both (or even more) relics assigned to the character (see second screenshot)

## Related Issue

* Closes #184 

## Checklist

- [x] I have added commit messages that are descriptive and meaningful.
- [x] I have tested the changes locally.
- [ ] I have reviewed the code changes.

## Screenshots

2024-04-05 15 59 57 fribbels github io 216ac1885fed
2024-04-05 16 09 16 fribbels github io 82d6d0237da4

### CODE REVIEW

**Comment by Kenste** [comment]
I just had a look at it, and could change the `setRelic` function to do pretty much the same I currently do in my change (and revert the current change, keeping the `forceCharacterTabUpdate()`).

**Comment by fribbels** [comment]
Thanks for the bug fix! Tested it out and the fix works, though this functionality is probably better suited to be in DB itself, since there might be other cases where we'd have to do this same logic for adding relics in the future.

@Kenste Also we have a dev channel on discord https://discord.gg/QxbWveAx if you're available to join, can usually get faster responses there vs pr comments

**Comment by Kenste** [comment]
Just updated the PR description to include two more issues I found and could fix with the latest commit.

I isolated the original `setRelic` logic to avoid recursion with the other functions (e.g. `DB.setRelic` -> `DB.equipRelic` -> `DB.setRelic` etc.) and wrapped it with consistency checks, for the "public" use. 

---- 

Yeah, I figured that and will join! :D 
I just prefer having everything in one location to not have to jump between discord, git etc. to make sense of issues and discussions.

**Comment by fribbels** [comment]
Thanks again, sent to beta & invited you to the kanban board

**Pull request merged**
