### PR TITLE
Change maxed main stat toggle to dropdown

### PR DESCRIPTION
**Pull request by Sethyboy0**
## Description

- Changed "maxed main stat" toggle on the optimizer to a dropdown that allows you to pick what level the relics are upscaled to. The current values are 3/6/9/12/15 with a default value of 12. Anything below 9 isn't very useful but it doesn't cost anything to add.
- Added some typing stuff to get TS to stop bitching at me. I can remove it from the PR if you don't want it.
- Moved some relic calculation code to a utils file to share it between this dropdown's effects and the relic page.

The reasoning behind this is to help newer players like myself, my wife, and my friend who are just hitting TL 65 and are starting to seriously push the endgame modes. Relic exp costs scale exponentially while the gains are mostly linear and for the price of a +15 relic you can have 2 +12s or 4 +9s. This dropdown lets us help determine which relics are worth using our resources on, especially as we deal with relics we know will later get replaced because of limited substat choices.

https://honkai-star-rail.fandom.com/wiki/Relic/EXP

Pic:
image

Optimizing my acheron with +15 selected (matches with master):
image

Now with +12 selected:
image

I also updated the help text, though there's probably a better way to word things:
image

Maybe calling it "Relic upscale level" and changing the bottom settings to say "minimum" would be better?

## Checklist

- [ ] I have added commit messages that are descriptive and meaningful.
- - I'll update the commits later if/when we actually want to merge it.
- [x] I have tested the changes locally.
- [x] I have reviewed the code changes.

### CODE REVIEW

**Comment by fribbels** [comment]
Sorry for dragging this out, I'll be focusing back on optimizer tab updates in the next patch and will get this in

**Comment by fribbels** [comment]
I'm planning some UI reorganization for this part of the page, so I wanted to shuffle some of the components around and figure out where to put this selector 

image

**Comment by Sethyboy0** [comment]
No worries. Let me know if I can help or if there's any changes I can make this to PR that would be useful.

**Comment by Sethyboy0** [comment]
Gave the name and description another go. Here's how it looks:

image

image

**Comment by fribbels** [comment]
I appreciate the typescript & doc update, code looks solid!

The only issue I saw was that defaulting to +12 would go against what existing users expect for behavior, so I'll go ahead adjust that to +15 unless you have a strong objection

**Comment by fribbels** [comment]
Going to merge this into beta so we can tweak ui stuff & get feedback, feel free to continue the conversation on this PR or on discord

**Comment by Sethyboy0** [comment]
I saw you changed the setting name. Don't forget to update the hint too.

**Comment by fribbels** [comment]
Yeah I was trying to find a title that fits on half the flex so we can fit another dropdown next to it lmao. Thanks for the reminder

image

**Pull request merged**
