### PR TITLE
Feature/multiple saved loadouts

### PR DESCRIPTION
**Pull request by halimtech**
# Pull Request

## Description
Adding the feature to save, view and equip old builds.

### Added
Two new modals were added. The modals are in TS since I saw that there is an ongoing migration towards that and the character type has been changed to accommodate the new old builds field.
- changed the character type to include builds
- changed the db to include the use cases of builds

## Checklist
- [x] I have added commit messages that are descriptive and meaningful.
- [x] I have tested the changes locally.
- [x] I have reviewed the code changes.

## Screenshots
image
When clicking "save build"
image
When clicking "view old build"
image

## Additional Notes
If there is a need to write tests let me know, but it was tested locally and it doesn't break anything in the state tree

### CODE REVIEW

**Comment by halimtech** [comment]
fixed merge conflicts

**Comment by fribbels** [comment]
For e7 for example my loadouts idea was having a separate grid containing all the previous builds' stats and ratings, which you could click on to preview the items

image

**Comment by halimtech** [comment]
I will work on it in the coming days, makes sense that we need to see who is losing their relics

**Comment by halimtech** [comment]
This is how the page will look like without choosing a build 
image

And then after selecting one the relics will show and it will indicate who is the current owner of the relic piece
image

**Comment by halimtech** [comment]
It looks better and more clear if the scores are shown 
image

**Comment by fribbels** [comment]
@halimtech I made some visual edits to reuse the CharacterPreview, which lets us show stats now

**Comment by fribbels** [comment]
Reviewed and checks look good, thanks so much for making this feature! Merging into beta but let me know if you have any feedback on the changes

Final displays:

image

image

image

**Pull request merged**
