### PR TITLE
feat: info page

### LINKED ISSUE #189: [Feature] "Info" page for optimizer/contributor info
### Motivation

Currently users have to click into the discord link / github link to find out more info about the optimizer & contributors. We could improve the project's visibility and invite more people to help out with the repo. Also would be a nice way to say thanks to everyone who's helped build this out.

### Objective

* Set up an "Info" tab and add it to the menu. 
* This should list out some general optimizer information, some links, and show the contributors. 
* Dynamically pull the contributor icons/urls from github and display a list of them. 
* List out some of the future items on the roadmap for interest

### PR DESCRIPTION
**Pull request by FI00ds**
# Pull Request

## Description

* Added information page with contributors, links, and roadmap items
* Added contributors, loaded automatically via GitHub REST API
* Added roadmap items, configured in ChangelogTab.tsx
* [ ] TODO?: add fallback for access when rate limited?

## Related Issue

Closes #189 

## Checklist

- [x] I have added commit messages that are descriptive and meaningful.
- [x] I have tested the changes locally.
- [x] I have reviewed the code changes.

## Screenshots

%pn_24-08-06-00-55

### CODE REVIEW

**Comment by FI00ds** [comment]
idk what to add for the GDPR/Cookie policy compliance

**Comment by fribbels** [comment]
image

I somewhat feel like we should just hardcode the contributor list & roadmap - These things don't update often enough to really necessitate a live api call

**Comment by FI00ds** [comment]
yeah roadmap is probably fine for hardcoding.
For the contributors it only costs 1 point to fetch them all anyways so you would basically never hit the rate limit (60 points / hour)
also:
> Dynamically pull the contributor icons/urls from github and display a list of them.
:ragey: but hardcoding is probably fine as well as long as we remember to update every so often

**Comment by FI00ds** [comment]
closing this now that you added the home page

**Pull request closed without merging**
