### PR TITLE
Vite Migration

### PR DESCRIPTION
**Pull request by elegant-jack**
I'm creating this pull request "earlier" to both document and discuss the progress on the migration.

As said in Discord, the plan is to:

> 1 - migrate to vite: because it integrates better with typescript. Webpack is nice but in my experience some things sometimes break between babel and typescript, I never had such a problem when using vite (it uses esbuild interally iirc)
> 1.1 - also it would be nice to introduce prettier and integrate it to eslint, that way we have a uniform code style
> 
> 2 - do a "dirty" migration: the idea is to just add types at first, not touch or refactor code, otherwise we will end up with a rewrite, and no one usually have the energy to finish one of those. There is a way to configure vite to ignore ts errors on build but show on dev, for webpack I'm not sure
> 2.1 - at first we define the core types (e.g. light cone/ character info), those along with the vite migration could be merged to main first.
> 2.2 - then we just add types to the component props
> 
> 3 - refactor: After typing everything, we will end up with mountain of errors. Its better to deal with then when everything is typed.
> 3.1 - After the type errors are dealt with, we could optionally configure more eslint rules to improve code quality, but that is very optional.

### CODE REVIEW

**Comment by cnojima** [comment]
@elegant-jack - can you change PR target from `main` to `beta`?  I believe @fribbels wants to control point releases directly.

**Comment by elegant-jack** [comment]
By the amount of conflicts I think it will be easier to start from sketch using beta as an starting point

**Comment by cnojima** [comment]
> By the amount of conflicts I think it will be easier to start from sketch using beta as an starting point

I just spent 30 mins or so trying to resolve conflicts and pretty much agree that, while not impossible, not worth the ongoing effort.

If you don't mind me making suggestions here, if it were me i would break this PR down into 3+ smaller PRs:
1. new branch from /beta to port src/types/* and any expressed types from constants, libs, components, etc.
2. new branch from /beta to port webpack > vite

after the above have settled and all the good stuff is in /main, new branches to atomically refactor js(x) > ts(x)
- DB
- store
- form
- character
- lightCones
- individual views/components

'course, this is just my $0.02.

**Comment by elegant-jack** [comment]
Closing this in favor of what you just suggested. I'll be coming with the PRs shortly

**Comment by elegant-jack** [comment]
I cooled my head and resolved the conflicts.

**Comment by elegant-jack** [comment]
I renamed this to vite migration for now. I think this could be merged as is. Otherwise further work would require other 30+ minute merge conflict solving.

**Comment by fribbels** [comment]
@elegant-jack My apologies for the merge conflicts - its been a crazy couple weeks trying to get all the updates out for the 2.0 patch. Things should be cooldown down now so I should be able to help out with this effort

**Comment by fribbels** [comment]
Testing it out, seems to hang before completion on some searches 
image

**Comment by fribbels** [comment]
Pressing Import relics / Import characters and relics runs into a db.js:567 Uncaught TypeError: objectHash is not a function

image

**Comment by fribbels** [comment]
Haven't found any other breaking errors other than the importer

**Comment by elegant-jack** [comment]
I think it is fixed. The problem was a vite resolving the object-hash namespace import in a strange way. I switch for a default import and it worked

**Comment by elegant-jack** [comment]
Wait a sec, I'll check if the other similiar imports are misbehaving

**Pull request merged**
